# Site settings
baseurl = "https://9bladed.com/"
themesDir = "themes"
languageCode = "en-us"
title = "Aesthetics of the Absurd"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "9bladed"

[params]
	name = "John Kehayias"
	description = "Stuff about things"
	bio = "Photography - Writing - Miscellany"
	# Enter optionally your twitter account
	twitter = "9bladed"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = ["css/cactus_custom.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Writing, photographing, thinking."
	tweet = "Tweet this"
	share = "Share this"
	# 404 page
	title404 = "404 - Congratulations, you've achieved a new high score!"
	subtitle404 = "Sadly, your prize is this error page."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
        # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
        socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
        twitter  = "https://www.twitter.com/9bladed"
        #facebook = "https://www.facebook.com/"
        #dribble  = "https://www.dribbble.com/"
        instagram = "https://www.instagram.com/9bladed"
        flickr = "https://www.flickr.com/9bladed"
        500px = "https://500px.com/9bladed"
        github   = "https://www.github.com/podiki"

[[menu.main]]
    name = "Blog"
    url = "/post/"
[[menu.main]]
    name = "Essays"
    url = "/essay/"
[[menu.main]]
    name = "Photo Essays"
    url = "/photo-essay/"

[taxonomies]
        tag = "tags"
        category = "categories"
        series = "series"
